# Packages

Package is a way to organize related modules and sub-packages together.

Packages in Python can be visualized as directories containing Python scripts. Each script within the package is referred to as a module. These modules define functions, methods, and new Python types designed to tackle specific problems. With an extensive array of available packages, Python offers thousands of solutions for diverse tasks.

### Installing packages:

* !pip install package_name

### Importing packages:

Befor use a package you should import the package or a specfic module of the package using the import statement:

* import package_name


In [2]:
#E.g. using the numpy package 

!pip install numpy
import numpy

In the numpy package que have the array function:

**Note:** When you have a function inside a package, it needs to refer to the package.

In [4]:
numpy.array([1,2,3])

array([1, 2, 3])

### Referencing packages:

To simply this we can import a package and refer to it with a different name:

In [5]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

If we need only a specific function of a package, we can explicit it like this:

**Note:** In this case we don't need the use "numpy.array" only the function "array"

In [7]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

### Some useful Python packages:

Standard Library Packages:

* **os**: Provides a way to work with the operating system, allowing you to perform operations like file and directory manipulation.

* **sys**: Contains functions to interact with the Python runtime environment, such as command-line arguments and system-specific parameters.

* **datetime**: Offers classes for working with dates, times, and timedeltas, facilitating various time-related operations.

* **math**: Provides mathematical functions and constants, like trigonometric, logarithmic, and arithmetic operations.

* **random**: Offers functions for generating random numbers, useful for simulations, games, and other applications.

* **json**: Enables encoding and decoding JSON data, essential for working with APIs and data interchange.

* **csv**: Facilitates reading and writing Comma-Separated Values (CSV) files, a common format for data storage and exchange.

* **urllib**: Allows you to open URLs and fetch data from the internet, making it useful for web scraping and fetching data from APIs.

Popular Third-Party Packages:

* **numpy**: Provides powerful numerical computing capabilities, including support for arrays and mathematical functions.

* **pandas**: Offers data manipulation and analysis tools, particularly useful for working with tabular and time-series data.

* **matplotlib**: Enables plotting and visualization of data in various formats, helping to create charts and graphs.

* **requests**: Simplifies making HTTP requests, making it a popular choice for interacting with web APIs.

* **scikit-learn**: A comprehensive machine learning library that includes a wide range of algorithms and tools for data analysis and modeling.

* **tensorflow and pytorch**: Deep learning frameworks used for building and training neural networks.

* **flask and django**: Web frameworks for developing web applications, with Flask being lightweight and Django offering more features and structure.

* **beautifulsoup4**: Facilitates web scraping by parsing HTML and XML documents to extract data.