# NumPy

Is a powerful library for numerical computations. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently.

* Provide a alternative to the regular python list, the NumPy array

However, NumPy array is a new kind of Python type and have it own methods, for example:

In [1]:
phyton_list = [1,2,3]
phyton_list+phyton_list

[1, 2, 3, 1, 2, 3]

In [7]:
from numpy import array
numpy_array = array([1,2,3])
numpy_array+numpy_array

array([2, 4, 6])

**Note:** NumPy arrays: contain only one type

In [8]:
array([1,True,"Smith"])

array(['1', 'True', 'Smith'], dtype='<U11')

All different types of elements have been transformed into strings in the array.

### NumPy Subsetting

* It is similar to lists
* It has some peculiarities

In [11]:
number = array([1,2,3,4,5])


In [14]:
number > 2

array([False, False,  True,  True,  True])

In [15]:
number[number>2]

array([3, 4, 5])

### 2D NumPy Arrays

Provides support for multi-dimensional arrays and matrices.

In [17]:
np_2p = array([[1,2,3],
              [4,5,6]])
print(np_2p)

[[1 2 3]
 [4 5 6]]


In [18]:
np_2p.shape

(2, 3)

(**n** rows, **m** columns)

### Subsetting

In [22]:
np_2p = array([[1,2,3,4,5],
               [6,7,8,9,10]])

In [27]:
np_2p[0][2]

3

In [28]:
np_2p[0,2]

3

In [29]:
np_2p[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

### Basic Statistics

In [35]:
import numpy as np
np_2p = array([[1,2,3,4,5],
               [6,7,8,9,10]])

np.mean(np_2p[0,:])

3.0

In [36]:
np.median(np_2p)

5.5

In [37]:
np.std(np_2p)

2.8722813232690143

In [39]:
np.corrcoef(np_2p[0,:],np_2p[1,:])

array([[1., 1.],
       [1., 1.]])

### Generate data

np.random.normal(distribuition mean, distribuition standard deviation, number of samples

In [42]:
np.random.normal(1.75,0.20,10)

array([1.8023097 , 1.59978299, 1.81392864, 1.79233168, 1.78473112,
       1.98919687, 1.99694098, 1.27800587, 1.85799097, 1.45973313])